export const genreNames: { [key: string]: string } = {
  'history': 'Исторический',
  'horror': 'Ужасы',
  'scifi': 'Sci-fi',
  'stand-up': 'Выступление',
  'fantasy': 'Фантастика',
  'drama': 'Драма',
  'mystery': 'Мистика',
  'family': "Семейное",
  'comedy': 'Комедия',
  'romance': 'Романтика',
  'music': 'Музыка',
  'crime': 'Криминал',
  'tv-movie': 'TV-фильм',
  'documentary': 'Документальное',
  'action': 'Боевик',
  'thriller': 'Триллер',
  'western': 'Вестерн',
  'animation': 'Мультик',
  'war': 'Война',
  'adventure': 'Приключение'
};